
import type { Metadata } from 'next'
import StyledComponentsRegistry from '../registry/StyledComponentsRegistry'
import StyleSheetRegistry from '../registry/StyleSheetRegistry'
import StyledRegistry from '../registry/StyledComponentsRegistry'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
// const GlobalStyle = createGlobalStyle``

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
      <StyledComponentsRegistry>
        <StyleSheetRegistry>
          {children}
        </StyleSheetRegistry>
      </StyledComponentsRegistry>
      </body>
    </html>
  )
}
