import '@coldsurfers/hotsurf/global.css'
import type { Metadata } from 'next'
import StyledComponentsRegistry from '../registry/StyledComponentsRegistry'
import StyleSheetRegistry from '../registry/StyleSheetRegistry'
import RegistryProvider from '../registry/RegistryProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <RegistryProvider
          registries={[StyledComponentsRegistry, StyleSheetRegistry]}
        >
          {children}
        </RegistryProvider>
      </body>
    </html>
  )
}
