name: deploy surflog production website

on:
  push:
    branches:
      - main
    paths:
      - 'packages/surflog/**'
  workflow_dispatch:

env:
  NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
  NOTION_DATABASE_ID: ${{ secrets.NOTION_BLOG_DATABASE_ID }}
  CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
  CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
  SITE_URL: ${{ secrets.SITE_URL }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_SURFLOG_PROJECT_ID }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: "yarn"
      - run: npm config set @coldsurfers:registry https://npm.pkg.github.com/
      - run: npm config set '//npm.pkg.github.com/:_authToken' ${{ secrets.GITHUB_TOKEN }}
      - run: yarn super-install
      - run: yarn build
        working-directory: ./packages/surflog
      - run: npx vercel pull --yes --token ${{ secrets.VERCEL_TOKEN }}
        working-directory: ./packages/surflog
      - run: npx vercel build --prod
        working-directory: ./packages/surflog
      - run: npx vercel deploy --prod --prebuilt --token ${{ secrets.VERCEL_TOKEN }}
        working-directory: ./packages/surflog