name: deploy metronome web preview website

on:
  pull_request:
    paths:
      - 'packages/metronome-web/**'

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_METRONOME_WEB_PROJECT_ID }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        # with:
#          cache: "yarn"
      - run: npm config set @coldsurfers:registry https://npm.pkg.github.com/
      - run: npm config set '//npm.pkg.github.com/:_authToken' ${{ secrets.GITHUB_TOKEN }}
      - run: yarn super-install
      - run: yarn build
        working-directory: ./packages/metronome-web
      - run: npx vercel pull --yes --token ${{ secrets.VERCEL_TOKEN }}
        working-directory: ./packages/metronome-web
      - run: npx vercel build
        working-directory: ./packages/metronome-web
      - run: npx vercel deploy --prebuilt --token ${{ secrets.VERCEL_TOKEN }}
        working-directory: ./packages/metronome-web
